server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Compresión Gzip activada para máximo rendimiento
    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri.html $uri/ /index.html =404;
    }

    # Caché optimizada para recursos multimedia y estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|pdf)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }

    error_page 404 /index.html;
}
